export const USER_ROLES = {
  ADMIN: 'ADMIN',
  SUPPLIER: 'SUPPLIER',
  BUYER: 'BUYER',
  VERIFIER: 'VERIFIER',
  LOGISTICS_PARTNER: 'LOGISTICS_PARTNER'
};

export const LISTING_STATUS = {
  DRAFT: 'DRAFT',
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  VERIFIED: 'VERIFIED',
  ACTIVE: 'ACTIVE',
  MATCHED: 'MATCHED',
  SOLD: 'SOLD',
  EXPIRED: 'EXPIRED'
};

export const TRANSACTION_STATUS = {
  INITIATED: 'INITIATED',
  ESCROW_PENDING: 'ESCROW_PENDING',
  ESCROW_LOCKED: 'ESCROW_LOCKED',
  IN_TRANSIT: 'IN_TRANSIT',
  DELIVERED: 'DELIVERED',
  COMPLETED: 'COMPLETED',
  DISPUTED: 'DISPUTED',
  CANCELLED: 'CANCELLED'
};

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500
};
